name = "giraffe"
main = "src/server/index.ts"
compatibility_date = "2026-04-01"
workers_dev = false
preview_urls = false

[observability]
enabled = true

[dev]
port = 7045

[assets]
directory = "./dist/client"
binding = "ASSETS"
run_worker_first = ["/api", "/api/*"]
not_found_handling = "single-page-application"

[[routes]]
pattern = "giraffe.hexly.ai"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "giraffe-db"
database_id = "02138e3b-9b18-48b3-95b3-fa8bccd8faa8"
